config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get '/:locale' => 'sessions#home'
    root 'sessions#home'
    get 'tables/plan'
    resources :tables
    get 'admin/index'
    resources :guests
    get '/wca_callback' => 'sessions#create'
    get '/signin' => 'sessions#new', :as => :signin
    post '/signin_with_wca' => 'sessions#signin_with_wca', :as => :signin_with_wca
    get '/signout' => 'sessions#destroy', :as => :signout
    get "/pages/:id" => "high_voltage/pages#show", :as => :page, :format => false
  end
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :table, optional: true
  mount_uploader :avatar, AvatarUploader
  validates_inclusion_of :country_iso2, in: Country.real.map(&:iso2).freeze
  INVITERS = %w(fifi manou).freeze
  validates_inclusion_of :invited_by, in: INVITERS
  validates_presence_of :name
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_unless_admin!
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:name, :avatar, :description, :country_iso2, :confirmed, :remove_avatar, :invited_by)
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= simple_form_for guest do |form| %>
  <% if guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.input :name %>
  <% unless guest.avatar.file.nil? %>
    <%= public_image_tag(guest.avatar.mini_thumb.url) %>
    <%= form.input :remove_avatar, as: :boolean %>
    <br />
    You can upload a new image file below:
    <br />
  <% end %>
  <%= form.file_field :avatar %>
  <%= form.input :description %>
  <%= form.input :invited_by, collection: Guest::INVITERS  %>
  <%= form.input :country_iso2, collection: Country.real, label_method: lambda { |c| c.name }, value_method: lambda { |c| c.iso2 } %>
  <%= form.input :confirmed %>

  <div class="actions">
    <%= form.button :submit %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guests</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Description</th>
      <th>Country</th>
      <th>Confirmed</th>
      <th>Invited by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td>
          <%= public_image_tag(guest.avatar.mini_thumb.url, class: "avatar-thumbnail") %>
        </td>
        <td><%= guest.name %></td>
        <td><%= guest.description %></td>
        <td><%= flag_icon(guest.country_iso2) %></td>
        <td><%= guest.confirmed %></td>
        <td><%= guest.invited_by %></td>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest', new_guest_path %>

app/views/guests/new.html.erb
<h1>New Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guest.name %> <%= flag_icon(@guest.country_iso2) %>
</p>

<% if @guest.avatar.file.nil? %>
  <strong>L'utilisateur n'a pas de photo.</strong>
<% else %>
  <%= public_image_tag(@guest.avatar.url) %>
<% end %>

<p>
  <strong>Description:</strong>
  <%= @guest.description %>
</p>

<p>
  Invited by <%= @guest.invited_by %> and <%= @guest.confirmed ? "confirmed" : "not confirmed" %>.
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>