config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get '/:locale' => 'sessions#home'
    root 'sessions#home'
    get 'tables/plan'
    resources :tables
    get 'admin/index'
    resources :guests
    get '/wca_callback' => 'sessions#create'
    get '/signin' => 'sessions#new', :as => :signin
    post '/signin_with_wca' => 'sessions#signin_with_wca', :as => :signin_with_wca
    get '/signout' => 'sessions#destroy', :as => :signout
    get "/pages/:id" => "high_voltage/pages#show", :as => :page, :format => false
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # TODO: protect the plan action
  before_action :authenticate_user!, except: [:plan]
  before_action :redirect_unless_admin!, except: [:plan]
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  def plan
  end

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: 'Table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:name, :guests_ids)
    end
end

app/helpers/tables_helper.rb
module TablesHelper
  def guests_to_options
    Guest.all.map { |g| { value: g.id, name: g.name, thumb: g.avatar.mini_thumb.url, invited_by: g.invited_by } }.to_json.html_safe
  end
end

app/views/tables/_form.html.erb
<%= simple_form_for(table, wrapper: :horizontal_form) do |form| %>
  <% if table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.input :name %>

  <%= form.input :guests_ids, input_html: { class: "enable-selectize" } %>

  <%= form.button :submit %>
<% end %>
<% content_for :additional_scripts do %>
  <%= javascript_pack_tag "selectize", 'data-turbolinks-track': 'reload'  %>
<% end %>
<script>
  let renderFunc = function(type, data) {
    let $div = $('<div class="wedding-guest"> <div class="avatar-thumbnail"></div> <div class="info"><div class="name"></div><div class="invited_by"></div></div> </div>');
    $div.find(".name").text(data.name);
    $div.find(".avatar-thumbnail").css('background-image', 'url("<%= root_url %>/' + data.thumb + '")');
    $div.find(".invited_by").text(data.invited_by);
    return $div[0].outerHTML;
  };
  window.manouetfifi.enableSelectize(<%= guests_to_options %>, renderFunc);
</script>

app/views/tables/_guest_fields.html.erb
<div class="nested-fields">
  <%= f.input :id, collection: Guest.order(:name), prompt: "Choose a guest" %>
  <%= link_to_remove_association "remove guest", f %>
</div>

app/views/tables/edit.html.erb
<h1>Editing Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tables</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= table.name %></td>
        <td><%= link_to 'Show', table %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Back', tables_path %>

app/views/tables/plan.html.erb
<h1>Plan de tables</h1>

<canvas id="tables-map" width="800" height="600"></canvas>

<% content_for :additional_scripts do %>
  <%= javascript_pack_tag "tables_map", 'data-turbolinks-track': 'reload'  %>
<% end %>
<script>
$(function() {
  window.manouetfifi.enableMap("tables-map");
});
</script>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @table.name %>
</p>

<% if @table.guests.any? %>
  <div class="list-group">
    <% @table.guests.each do |g| %>
      <%= render "shared/guest", guest: g, extra_classes: "list-group-item" %>
    <% end %>
  </div>
<% else %>
  <p>Pas d'invités à cette table</p>
<% end %>

<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>