config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    get '/:locale' => 'sessions#home'
    root 'sessions#home'
    get 'tables/plan'
    resources :tables
    get 'admin/index'
    resources :guests
    get '/wca_callback' => 'sessions#create'
    get '/signin' => 'sessions#new', :as => :signin
    post '/signin_with_wca' => 'sessions#signin_with_wca', :as => :signin_with_wca
    get '/signout' => 'sessions#destroy', :as => :signout
    get "/pages/:id" => "high_voltage/pages#show", :as => :page, :format => false
  end
end

app/views/layouts/_basic_body.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'stylesheets', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :additional_scripts %>
    <!-- TODO
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    -->
    <meta name="theme-color" content="#ffffff">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Philippe Virouleau">
  </head>

  <% has_footer ||= false %>
  <body class="<%= "has_footer" if has_footer %>">
    <%= yield %>
  </body>
</html>

app/views/layouts/_flash.html.erb
<div id="flash-alerts" class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert <%= bootstrap_class_for message_type %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted m-0">
      <a href="https://github.com/viroulep/manouetfifi" target="_blank">
        <i class="fa fa-github"></i>
      </a>
      |
      <% if current_user %>
        <%= link_to(fa_icon("sign-out"), signout_path) %>
        <% if current_user.admin? %>
          | <%= link_to(fa_icon("cogs"), admin_index_path) %>
        <% end %>
      <% else %>
        <%= link_to(fa_icon("sign-in"), signin_path) %>
      <% end %>
    </p>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
  <nav class="navbar navbar-expand-sm">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main" aria-controls="navbar-main" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-container w-100">
      <div id="navbar-main" class="collapse navbar-collapse justify-content-sm-center">
        <ul class="navbar-nav">
          <%= render "shared/nav_item", path: root_url,
            icon_name: "home", text: t('navigation.home') %>
          <%= render "shared/nav_item", path: page_path("location"),
            icon_name: "map-marker", text: t('navigation.places') %>
          <%= render "shared/nav_item", path: page_path("accommodation"),
            icon_name: "bed", text: t('navigation.accommodation') %>
          <%= render "shared/nav_item", path: page_path("schedule"),
            icon_name: "calendar", text: t('navigation.schedule') %>
          <%= render "shared/nav_item", path: page_path("under_construction"),
            icon_name: "users", text: t('navigation.guests') %>
          <%= render "shared/nav_item", path: page_path("contact"),
            icon_name: "envelope", text: t('navigation.contact') %>
          <li class="nav-item dropdown d-flex">
            <a href="#" class="dropdown-toggle ml-4 mx-sm-2 my-2 my-sm-auto" data-toggle="dropdown" data-hover="dropdown">
              <% active_locale_info = Locales::AVAILABLE[I18n.locale] %>
              <%= flag_icon(active_locale_info[:flag_id]) %>
              <span class="caret"></span>
            </a>
            <div class="dropdown-menu" role="menu">
              <% Locales::AVAILABLE.each do |l, data| %>
                <%= link_to flag_icon(data[:flag_id]), url_for(locale: l), class: "nav-link dropdown-item" %>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<%= render 'layouts/basic_body', has_footer: true do %>
  <%= render 'layouts/navigation' %>

  <div id="main-container">
    <%= render 'layouts/flash' %>

    <div class="container">
      <%= yield %>
    </div>
  </div>

  <%= render 'layouts/footer' %>
<% end %>

app/views/layouts/blank.html.erb
<%= render 'layouts/basic_body' do %>
  <%= yield %>
<% end %>